<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.2.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.9.0" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UniversityManagementSystem.Core\UniversityManagementSystem.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Colleges\Commands\CreateCollege\" />
    <Folder Include="Features\Colleges\Commands\DeleteCollege\" />
    <Folder Include="Features\Colleges\Commands\UpdateCollege\" />
    <Folder Include="Features\Colleges\Queries\GetColleges\" />
    <Folder Include="Features\Colleges\Queries\GetCollegeById\" />
    <Folder Include="Features\Colleges\Queries\GetCollegeWithDepartments\" />
    <Folder Include="Features\Courses\Commands\CreateCourse\" />
    <Folder Include="Features\Courses\Commands\AssignInstructor\" />
    <Folder Include="Features\Courses\Commands\UpdateCourse\" />
    <Folder Include="Features\Courses\Queries\GetCourses\" />
    <Folder Include="Features\Courses\Queries\GetCourseById\" />
    <Folder Include="Features\Courses\Queries\GetCoursePrerequisites\" />
    <Folder Include="Features\Users\Commands\CreateUser\" />
    <Folder Include="Features\Users\Commands\DeleteUser\" />
    <Folder Include="Features\Users\Commands\UpdateUser\" />
    <Folder Include="Features\Users\Queries\GetUsers\" />
    <Folder Include="Features\Users\Queries\GetUserById\" />
    <Folder Include="Features\Users\Queries\GetUserRoles\" />
    <Folder Include="Validators\AuthValidators\" />
    <Folder Include="Validators\CollegeValidators\" />
    <Folder Include="Validators\CourseValidators\" />
    <Folder Include="Validators\UserValidators\" />
  </ItemGroup>

</Project>
